language: generic
os: linux
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - git
      - liblapack-dev
      - libblas-dev
      - libatlas-base-dev
      - libarpack2-dev
      - libarpack++2-dev
      - libblas-dev
      - libatlas-base-dev
install:
    - wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm.sh | bash -s
    # annoying pip fix
    - export BOTO_CONFIG=/tmp/bogusvalue
script:
    - bash generate-makefile.sh
    - cd edupack && make && cd ../
    - bin/x86_64/edupack
    - cat bin/x86_64/edupack/plot.in